### ISSUE TITLE
使用真寻bot加载报错

### ISSUE THREAD

**Issue by mas-alone** [lgc2333/nonebot-plugin-autoreply#4]
排查了没有思路..
环境是Win11 py3.8

02-22 15:23:14 [ERROR] nonebot | Failed to import "nonebot_plugin_autoreply"
Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.8\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
 File "C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "d:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-gM3lmNrj-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\zhenxun_bot\plugins\nonebot_plugin_autoreply\__init__.py", line 3, in <module>
    from .__main__ import *  # noqa
  File "D:\zhenxun_bot\plugins\nonebot_plugin_autoreply\__main__.py", line 37, in <module>
    will_check: Iterable[tuple[Unpack[TArgs]]],
TypeError: 'type' object is not subscriptable

**Comment by lgc2333** [comment]
已发版

**Comment by mas-alone** [comment]
> 已发版

我笨比了，谢谢大哥！
