### ISSUE TITLE
报错 f2s

### ISSUE THREAD

**Issue by purelolly** [lgc2333/nonebot-plugin-autoreply#7]
04-29 23:31:04 [ERROR] nonebot | Failed to import "nonebot_plugin_autoreply"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/nonebot2/MIbot/./bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot_plugin_autoreply/__init__.py", line 3, in <module>
    from . import __main__ as __main__
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot_plugin_autoreply/__main__.py", line 30, in <module>
    from nonebot_plugin_autoreply.util import VarDictType, get_var_dict, replace_message_var
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot_plugin_autoreply/util.py", line 4, in <module>
    from nonebot.adapters.onebot.utils import f2s
ImportError: cannot import name 'f2s' from 'nonebot.adapters.onebot.utils' (/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/adapters/onebot/utils.py)

**Comment by TomorrowLost** [comment]
04-29 23:31:04 [ERROR] nonebot | Failed to import "nonebot_plugin_autoreply"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/nonebot2/MIbot/./bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot_plugin_autoreply/__init__.py", line 3, in <module>
    from . import __main__ as __main__
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot_plugin_autoreply/__main__.py", line 30, in <module>
    from nonebot_plugin_autoreply.util import VarDictType, get_var_dict, replace_message_var
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot_plugin_autoreply/util.py", line 4, in <module>
    from nonebot.adapters.onebot.utils import f2s
ImportError: cannot import name 'f2s' from 'nonebot.adapters.onebot.utils' (/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/adapters/onebot/utils.py)

**Comment by lgc2333** [comment]
nb2什么版本 onebot适配器什么版本

**Comment by lgc2333** [comment]
请尝试 `pip install nonebot2 nonebot-adapter-onebot -U`

**Comment by purelolly** [comment]
> nb2什么版本 onebot适配器什么版本

2.0.0.rc4  OneBot V11

**Comment by lgc2333** [comment]
请尝试 `pip install nonebot-adapter-onebot -U`

**Comment by purelolly** [comment]
> 请尝试 `pip install nonebot-adapter-onebot -U`

没有任何变化

**Comment by lgc2333** [comment]
今晚修，睡觉2023年5月2日 上午6:36，TomorrowLost ***@***.***>写道：

请尝试 pip install nonebot-adapter-onebot -U

没有任何变化

**Comment by purelolly** [comment]
> pip install nonebot-adapter-onebot -U

已经好了，是我的操作问题，没有进入虚拟环境
